name: YMKitX Checks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }} / ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  spm_tests_xcode:
    name: SPM Tests (Xcode ${{ matrix.XCODE_VERSION }})
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        XCODE_VERSION: ["16.4"]
        OS: [macos-15]
        DESTINATION:
          - "platform=iOS Simulator,name=iPhone 16 Pro Max,OS=18.5"
          - "platform=macOS"
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select -switch "/Applications/Xcode_${{ matrix.XCODE_VERSION }}.app"
      - name: Run Tests
        run: |
          xcodebuild \
          clean \
          test \
          -showBuildTimingSummary \
          -scheme YMKitX-Package \
          -destination "${{ matrix.DESTINATION }}" \
          | xcpretty && exit ${PIPESTATUS[0]}
  spm_tests_swift:
    name: SPM Tests (Swift on ${{ matrix.OS }})
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: [macos-15, ubuntu-24.04]
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
      - name: Select Xcode Version (macOS Only)
        if: ${{ matrix.OS == 'macos-15' }}
        run: sudo xcode-select -switch "/Applications/Xcode_16.4.app"
      - name: Run Tests
        run: swift test
